# Generated by Django 4.0.6 on 2022-07-25 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_options_recipe_pub_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Рецепт в корзине', 'verbose_name_plural': 'Корзина рецептов'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'default_related_name': 'favorites', 'ordering': ('user',), 'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
    ]
